### ISSUE TITLE
Crashes immediately

### ISSUE THREAD

**Issue by PikalaxALT** [meanmail/requirements#15]
**Describe the bug**
Immediate exception upon launching PyCharm 2019.3.

**To Reproduce**
1. Launch PyCharm
2. ???
3. ~~Profit~~ Exception

**Expected behavior**
Not an exception, that's for sure

**Screenshots**
Not applicable

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 10 (1909)
 - Product: PyCharm Professional
 - Version: PY-193.5233.109
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version e.g. 2019.6.0.2

**Additional context**

```
com.intellij.diagnostic.PluginException: Incorrect language specified in <fileType> for requirements.txt, should be requirements.txt, actual null [Plugin: ru.meanmail.plugin.requirements]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:497)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:464)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1269)
	at com.intellij.psi.impl.cache.impl.id.IdIndexImpl.getVersion(IdIndexImpl.java:25)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:349)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5300(FileBasedIndexImpl.java:107)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2448)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:173)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:161)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:122)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by meanmail** [comment]
Thanks for reporting the bug

**Comment by mcarans** [comment]
I have the same error.

**Comment by meanmail** [comment]
In two days, the fixed version will be available for download. Need to wait for confirmation from Jetbrains

**Comment by meanmail** [comment]
Release 2019.6.1 allowed to download!
[About release](https://meanmail.dev/post/2)

**Comment by mcarans** [comment]
@meanmail I have installed 2019.6.1 but still get the error when I try to upgrade a package using the requirements plugin:

```
com.intellij.diagnostic.PluginException: Incorrect language specified in <fileType> for requirements.txt, should be requirements.txt, actual null [Plugin: ru.meanmail.plugin.requirements]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:497)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:464)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1269)
	at com.intellij.psi.impl.cache.impl.id.IdIndexImpl.getVersion(IdIndexImpl.java:25)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:349)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5300(FileBasedIndexImpl.java:107)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2448)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:173)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:161)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:122)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by meanmail** [comment]
@mcarans Thanks for the feedback. This error should not affect the operation of the plugin :thinking: The revised version will be available in two business days

**Comment by meanmail** [comment]
2016.6.2 available for download

**Comment by mcarans** [comment]
I don't see the error now thanks. I do still have the problem that when upgrading packages through the plugin, reindexing doesn't occur so have created a new issue for that:
https://github.com/meanmail/requirements/issues/16
